require "./message"

module Swim
  enum TimeoutType
    DirectPing
    IndirectPingReq
  end

  # The base module for outputs generated by the protocol.
  module Effect; end

  record SendMessage, address : String, message : Message do
    include Effect
  end

  record ScheduleTimeout, duration : Time::Span, type : TimeoutType, seq : UInt64 do
    include Effect
  end
end
